.\" $Header: /net/yquem/devel/caml/repository/bigbro/doc/bigbro.1,v 1.2 2001/03/06 15:05:14 fpottier Exp $

.TH BIGBRO 1

.SH NAME
bigbro \- the Big Brother www link checker


.SH SYNOPSIS
.B bigbro
[
options
]
url1 url2 ...

.SH DESCRIPTION

Big Brother is used to verify links between documents written in the
HTML language. It comes with complete documentation in HTML,
PostScript and PDF formats. A summary of Big Brother's command line
switches can be obtained by typing
.br
				bigbro -help
.br

Please refer to the documentation for more details. If you do not have
access to it, please contact the author.

.SH FILES

.TP \w'/usr'un
.I /usr/doc/bigbro/html/doc.htm
Big Brother's documentation, in HTML format.
.TP
.I /usr/doc/bigbro/doc.ps
The same, in PostScript format.
.TP
.I /usr/doc/bigbro/doc.pdf
The same, in PDF (Adobe Acrobat) format.

.SH AUTHOR
.nf
Francois Pottier
Email: Francois.Pottier@inria.fr
URL: http://pauillac.inria.fr/~fpottier/
.fi

